name: rl
channels:
  - nvidia
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=12.4
  - torchvision
  - pytorch-lightning
  - stable-baselines3
  - gymnasium
  - pygame
  - box2d-py
  - jupyter
  - tensorboard
  - seaborn